# Generated by Django 4.1.4 on 2022-12-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.TextField(default=None, max_length=30),
        ),
    ]
