# Generated by Django 4.1.4 on 2022-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_company_jobpost_jobsite_recruiter_delete_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='response',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='companyName',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.ManyToManyField(blank=True, to='jobs.category'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='companyName',
            field=models.ManyToManyField(to='jobs.company'),
        ),
    ]
