# Generated by Django 4.1.4 on 2022-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobpost_category_remove_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stack',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.TextField(),
        ),
    ]
