# Generated by Django 4.1.4 on 2022-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_category_name_alter_company_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(),
        ),
    ]
