# Generated by Django 4.1.4 on 2022-12-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_origin',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='stack',
        ),
    ]
