# Generated by Django 4.1.4 on 2022-12-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobpost_locations_jobpost_post_origin_jobpost_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.TextField(blank=True, default=None),
        ),
    ]
