# Generated by Django 4.1.4 on 2022-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_company_locations_alter_jobpost_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stack',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='response',
            field=models.TextField(blank=True, default=None),
        ),
    ]
