# Generated by Django 4.1.4 on 2022-12-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_company_response_alter_jobpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
