# Generated by Django 4.1.4 on 2022-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
