# Generated by Django 4.1.4 on 2022-12-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stack',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(),
        ),
    ]
