# Generated by Django 4.1.4 on 2022-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobpost_category_alter_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
