# Generated by Django 4.1.4 on 2022-12-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_company_response_alter_jobpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(default='1111'),
        ),
    ]
