# Generated by Django 4.1.4 on 2022-12-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True, default='111'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='response',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stack',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
