# Generated by Django 4.1.4 on 2022-12-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobpost_salary_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='locations',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='stack',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.TextField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
