# Generated by Django 4.1.4 on 2022-12-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_category_name_alter_company_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.CharField(max_length=30),
        ),
    ]
