# Generated by Django 4.1.4 on 2022-12-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_alter_jobpost_category_alter_jobpost_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='companyName',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.ManyToManyField(blank=True, to='jobs.category'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='companyName',
            field=models.ManyToManyField(to='jobs.company'),
        ),
    ]
