# Generated by Django 4.1.4 on 2022-12-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_remove_jobpost_category_remove_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
    ]
