# Generated by Django 4.1.4 on 2022-12-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(blank=True, default=111),
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='companyName',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
