# Generated by Django 4.1.4 on 2022-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_jobpost_salary_remove_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(default=111),
        ),
    ]
