# Generated by Django 4.1.4 on 2022-12-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_alter_jobpost_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='companyName',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
