# Generated by Django 4.1.4 on 2022-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
